### ISSUE TITLE
Creating/Storing inputs on Events page

### ISSUE THREAD

**Issue by aryatyagi14** [aryatyagi14/Tonight.#3]
Once we actually have a page that opens from the button click, we need to add fields to enter information about the event. I will list the info we need the person to input to create an event.

-Event Name 
-Event Description
-Start Time and Expected Duration (if we can make this a drop down selection where you can choose a time that would be great!)
-How many people they want to join the event (should be categories: 1, 2-5, 5-10, 10+)

These should just be stored in local variables for now. Later we will actually create the event that will show up on the screen later.

**Comment by RohoCodo** [comment]
Just finished this. We can talk about how the event card and add event page should look. It works in adding events locally, but we need to create our own Firebase for Tonight for others to see published events
